#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf &

numlockx on &
xsetroot -cursor-name left_ptr &
setxkbmap -layout us,il -variant symbolic, -option grp:alt_shift_toggle
xset s off -dpms &

bspc monitor -d 01 02 03 04 05 06 07 08 09 10 # I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d 󰇊 󰇋 󰇌 󰇍 󰇎

bspc config border_radius	 12
bspc config border_width         4
bspc config focused_border_color "#8DA5F2"
bspc config normal_border_color "#58475A"

bspc config window_gap		 6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Tor Browser" state=floating follow=on focus=on 


#xrandr --output DP-2 --primary --left-of HDMI-1  --rate 165 &
while :; do feh --bg-scale -z /media/BigBoyDisk/Wallpapers; sleep 900; done &
polybar -r Gaybar &
polybar -r monitor2 &
dunst &
flameshot
