[font]
size = 10
[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[colors]

[window]
opacity = 0.90
dynamic_title = true
title = "Terminal"
[cursor]
style = {shape = "Block", blinking = "On"}
blink_interval = 500
unfocused_hollow = true
thickness = 0.20
